<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boek [
	<!ELEMENT boek (boek_id, titel, schrijver, uitgever, isbn_nr)>
	<!ELEMENT boek_id (#PCDATA)>
	<!ELEMENT titel (#PCDATA)>	
	<!ELEMENT schrijver (#PCDATA)>
	<!ELEMENT uitgever (#PCDATA)>
	<!ELEMENT isbn_nr (#PCDATA)>
]>
<boek>
	<boek_id>1</boek_id>
	<titel>
	Linux in A Nutshell : A Desktop Quick Reference (3rd Edition)
	</titel>
	<schrijver>
	Ellen Siever (Editor), Jessica P. Hekman, Stephen Figgins, Stephen Spainhour
	</schrijver>
	<uitgever>O' Reilly</uitgever>
	<isbn_nr>2</isbn_nr>
 </boek>

