=== switch87/VDAB/XML/bestanden/3_21_mixed_content.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="http://www.vdab.be/XML" 
		   targetNamespace="http://www.vdab.be/XML" 
		   elementFormDefault="qualified">
	<xs:simpleType name="schrijverType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="schrijversType" mixed="true">
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="schrijver" type="schrijverType"/>
			</xs:sequence>
	</xs:complexType>
	<xs:complexType name="boekType">
		<xs:sequence>
			<xs:element name="boek_id" type="xs:integer"/>
			<xs:element name="titel" type="xs:string"/>
			<xs:element name="schrijvers" type="schrijversType"/>
			<xs:element name="uitgever" type="xs:string"/>
			<xs:element name="isbn_nr" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="boek" type="boekType"/>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_22_mixed_content.xml
<?xml version="1.0" encoding="UTF-8"?>
<boek xmlns="http://www.vdab.be/XML" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	  xsi:schemaLocation="http://www.vdab.be/XML 3_21_mixed_content.xsd">
	<boek_id>404</boek_id>
	<titel>Teach Yourself C# Web Programming in 21 days</titel>
	<schrijvers>
		Samenwerking tussen
			<schrijver>Philip Syme</schrijver>
		en
			<schrijver>Peter Aitken</schrijver>
	</schrijvers>
	<uitgever>Sams</uitgever>
	<isbn_nr>0672322358</isbn_nr>
</boek>
