=== switch87/VDAB/XML/bestanden/3_23_primary_key.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:bib="http://www.vdab.be/XML" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   targetNamespace="http://www.vdab.be/XML" 
		   elementFormDefault="qualified">
	<xs:complexType name="boekType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
			<xs:element name="schrijver" type="xs:string"/>
			<xs:element name="uitgever" type="xs:string"/>
			<xs:element name="isbn_nr" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="boek_id" type="xs:positiveInteger"/>
	</xs:complexType>
	<xs:complexType name="boekenType">
		<xs:sequence>
			<xs:element name="boek" type="bib:boekType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="boeken" type="bib:boekenType">
		<xs:key name="boekKey">
			<xs:selector xpath="bib:boek"/>
			<xs:field xpath="@boek_id"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_24_primary_key.xml
<?xml version="1.0" encoding="UTF-8"?>
<boeken xmlns="http://www.vdab.be/XML" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.vdab.be/XML 3_23_primary_key.xsd">
	<boek boek_id="404">
		<titel>Database Programming with C#</titel>
		<schrijver>Thomsen</schrijver>
		<uitgever>Apress</uitgever>
		<isbn_nr>1590590104</isbn_nr>
	</boek>
	<boek boek_id="405">
		<titel>Teach Yourself C# Web Programming in 21 days</titel>
		<schrijver>Philip Syme &amp;amp; Peter Aitken</schrijver>
		<uitgever>Sams</uitgever>
		<isbn_nr>0672322358</isbn_nr>
	</boek>
	<boek boek_id="403">
		<titel>visual C# .NET</titel>
		<schrijver>Price Gunderloy</schrijver>
		<uitgever>Sybex</uitgever>
		<isbn_nr>0782129110</isbn_nr>
	</boek>
	<boek boek_id="402">
		<titel>The PHP Anthology Object Oriented PHP Solution 1</titel>
		<schrijver>Harry Fuecks</schrijver>
		<uitgever>Sitepoint</uitgever>
 		<isbn_nr>0957921853</isbn_nr>
	</boek>
	<boek boek_id="401">
		<titel>The PHP Anthology - Volume II: Applications</titel>
		<schrijver>Harry Fuecks</schrijver>
		<uitgever>Sitepoint</uitgever>
		<isbn_nr>0957921845</isbn_nr>
	</boek>
	<boek boek_id="400">
		<titel>DHTML Utopia Modern Web Design using javascript &amp;amp; DOM</titel>
		<schrijver>Stuart Langridge</schrijver>
		<uitgever>Sitepoint</uitgever>
		<isbn_nr>0957921896</isbn_nr>
	</boek>
</boeken>
