=== switch87/VDAB/XML/bestanden/3_25_foreign_key.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:bib="http://www.vdab.be/XML" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vdab.be/XML" elementFormDefault="qualified">
	<xs:complexType name="boekType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
			<xs:element name="schrijver" type="xs:string"/>
			<xs:element name="uitgever" type="xs:string"/>
			<xs:element name="isbn_nr" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="boek_id" type="xs:positiveInteger"/>
	</xs:complexType>
	<xs:complexType name="klantType">
		<xs:sequence>
			<xs:element name="naam" type="xs:string"/>
			<xs:element name="boeknr" type="xs:positiveInteger" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="boekenType">
		<xs:sequence>
			<xs:element name="boek" type="bib:boekType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="klantenType">
		<xs:sequence>
			<xs:element name="klant" type="bib:klantType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="bibliotheekType">
		<xs:sequence>
			<xs:element name="boeken" type="bib:boekenType"/>
			<xs:element name="klanten" type="bib:klantenType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="bibliotheek" type="bib:bibliotheekType">
		<xs:key name="boekKey">
			<xs:selector xpath="bib:boeken/bib:boek"/>
			<xs:field xpath="@boek_id"/>
		</xs:key>
		<xs:keyref name="klantFkey" refer="bib:boekKey">
			<xs:selector xpath="bib:klanten/bib:klant/bib:boeknr"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_26_foreign_key.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliotheek xmlns="http://www.vdab.be/XML" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			 xsi:schemaLocation="http://www.vdab.be/XML 3_25_foreign_key.xsd">
	<boeken>
		<boek boek_id="405">
			<titel>Database Programming with C#</titel>
			<schrijver>Thomsen</schrijver>
			<uitgever>Apress</uitgever>
			<isbn_nr>1590590104</isbn_nr>
		</boek>
		<boek boek_id="404">
			<titel>
				Teach Yourself C# Web Programming in 21 days
			</titel>
			<schrijver>Philip Syme &amp;amp; Peter Aitken</schrijver>
			<uitgever>Sams</uitgever>
			<isbn_nr>0672322358</isbn_nr>
		</boek>
		<boek boek_id="403">
			<titel>visual C# .NET</titel>
			<schrijver>Price Gunderloy</schrijver>
			<uitgever>Sybex</uitgever>
			<isbn_nr>0782129110</isbn_nr>
		</boek>
		<boek boek_id="402">
			<titel>
				The PHP Anthology Object Oriented PHP Solution 1
			</titel>
			<schrijver>Harry Fuecks</schrijver>
			<uitgever>Sitepoint</uitgever>
			<isbn_nr>0957921853</isbn_nr>
		</boek>
		<boek boek_id="401">
			<titel>
				The PHP Anthology - Volume II: Applications
			</titel>
			<schrijver>Harry Fuecks</schrijver>
			<uitgever>Sitepoint</uitgever>
			<isbn_nr>0957921845</isbn_nr>
		</boek>
		<boek boek_id="400">
			<titel>
				DHTML Utopia Modern Web Design using javascript &amp;amp; DOM
			</titel>
			<schrijver>Stuart Langridge</schrijver>
			<uitgever>Sitepoint</uitgever>
			<isbn_nr>0957921896</isbn_nr>
		</boek>
	</boeken>
	<klanten>
		<klant>
			<naam>Jan</naam>
			<boeknr>401</boeknr>
			<boeknr>402</boeknr>
		</klant>
		<klant>
			<naam>Yasmina</naam>
			<boeknr>405</boeknr>
		</klant>	
		<klant>
			<naam>Kim</naam>
			<boeknr>402</boeknr>
			<boeknr>403</boeknr>
		</klant>
	</klanten>
</bibliotheek>
