=== switch87/VDAB/XML/bestanden/3_27_substitution1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.vdab.be/XML" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   targetNamespace="http://www.vdab.be/XML" 
		   elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="abstract_schrijver" abstract="true" type="xs:string"/>
	<xs:complexType name="boekType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
			<xs:element ref="abstract_schrijver"/>
			<xs:element name="uitgever" type="xs:string"/>
			<xs:element name="isbn_nr" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="boek_id" type="xs:positiveInteger"/>
	</xs:complexType>
		<xs:complexType name="bibliotheekType">
		<xs:sequence>
			<xs:element name="boek" type="boekType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="schrijver" type="xs:string" substitutionGroup="abstract_schrijver"/>
	<xs:element name="auteur" type="xs:string" substitutionGroup="abstract_schrijver"/>
	<xs:element name="biblio" type="bibliotheekType"/>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_28_substitution1.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblio xmlns="http://www.vdab.be/XML" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.vdab.be/XML 3_27_substitution1.xsd">
	<boek boek_id="405">
		<titel>Database Programming with C#</titel>
		<schrijver>Thomsen</schrijver>
		<uitgever>Apress</uitgever>
		<isbn_nr>1590590104</isbn_nr>
	</boek>
	<boek boek_id="404">
		<titel>Teach Yourself C# Web Programming in 21 days</titel>
		<auteur>Philip Syme &amp;amp; Peter Aitken</auteur>
		<uitgever>Sams</uitgever>
		<isbn_nr>0672322358</isbn_nr>
	</boek>
</biblio>
