=== switch87/VDAB/XML/bestanden/3_29_substitution2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.vdab.be/XML" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vdab.be/XML" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="product" abstract="true"/>
	<xs:complexType name="boekType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
			<xs:element name="schrijver" type="xs:string"/>
			<xs:element name="uitgever" type="xs:string"/>
			<xs:element name="isbn_nr" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="boek_id" type="xs:positiveInteger"/>
	</xs:complexType>
	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="author" type="xs:string"/>
			<xs:element name="publisher" type="xs:string"/>
			<xs:element name="isbn_no" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="book_id" type="xs:positiveInteger"/>
	</xs:complexType>
	<xs:complexType name="bibliotheekType">
		<xs:sequence>
			<xs:element ref="product" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="boek" type="boekType" substitutionGroup="product"/>
	<xs:element name="book" type="bookType" substitutionGroup="product"/>
	<xs:element name="biblio" type="bibliotheekType"/>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_30_substitution2.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblio xmlns="http://www.vdab.be/XML" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.vdab.be/XML  3_29_substitution2.xsd">
	<boek boek_id="405">
		<titel>Database Programming with C#</titel>
		<schrijver>Thomsen</schrijver>
		<uitgever>Apress</uitgever>
		<isbn_nr>1590590104</isbn_nr>
	</boek>
	<book book_id="404">
		<title>Teach Yourself C# Web Programming in 21 days</title>
		<author>Philip Syme &amp;amp; Peter Aitken</author>
		<publisher>Sams</publisher>
		<isbn_no>0672322358</isbn_no>
	</book>
</biblio>
