=== switch87/VDAB/XML/bestanden/3_31_substitution_group.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.vdab.be/XML" 
           xmlns="http://www.vdab.be/XML" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   elementFormDefault="qualified" 
		   attributeFormDefault="unqualified">
	<xs:element name="bib" abstract="true"/>
	<xs:complexType name="boekType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
			<xs:element name="schrijver" type="xs:string"/>
			<xs:element name="uitgever" type="xs:string"/>
			<xs:element name="isbn_nr" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="boek_id" type="xs:positiveInteger"/>
	</xs:complexType>
	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="author" type="xs:string"/>
			<xs:element name="publisher" type="xs:string"/>
			<xs:element name="isbn_no" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="book_id" type="xs:positiveInteger"/>
	</xs:complexType>	
	<xs:complexType name="bibliotheekType">
		<xs:sequence>
			<xs:element name="boek" type="boekType" 
			            maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="libraryType">
		<xs:sequence>
			<xs:element name="book" type="bookType" 
			            maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="library" substitutionGroup="bib" 
	            type="libraryType"/>
	<xs:element name="bibliotheek" substitutionGroup="bib" 
	            type="bibliotheekType"/>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_32_substitution_group.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns="http://www.vdab.be/XML" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		 xsi:schemaLocation="http://www.vdab.be/XML 3_31_substitution_group.xsd">
	<book book_id="405">
		<title>Database Programming with C#</title>
		<author>Thomsen</author>
		<publisher>Apress</publisher>
		<isbn_no>1590590104</isbn_no>
	</book>
	<book book_id="404">
		<title>Teach Yourself C# Web Programming in 21 days</title>
		<author>Philip Syme &amp;amp; Peter Aitken</author>
		<publisher>Sams</publisher>
		<isbn_no>0672322358</isbn_no>
	</book>
</library>
