=== switch87/VDAB/XML/bestanden/3_33_afgeleid_van_product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.vdab.be/XML" targetNamespace="http://www.vdab.be/XML" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="productType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger"/>
	</xs:complexType>
	<xs:element name="product" type="productType" abstract="true"/>
	<xs:complexType name="boekType">
		<xs:complexContent>
			<xs:extension base="productType">
				<xs:sequence>
					<xs:element name="schrijver" type="xs:string"/>
					<xs:element name="uitgever" type="xs:string"/>
					<xs:element name="isbn_nr" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="cdType">
		<xs:complexContent>
			<xs:extension base="productType">
				<xs:sequence>
					<xs:element name="uitvoerder" type="xs:string"/>
					<xs:element name="tekstschrijver" type="xs:string"/>
					<xs:element name="componist" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="bibliotheekType">
		<xs:sequence>
			<xs:element ref="product" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="boek" type="boekType" substitutionGroup="product"/>
	<xs:element name="cd" type="cdType" substitutionGroup="product"/>
	<xs:element name="biblio" type="bibliotheekType"/>
</xs:schema>

=== switch87/VDAB/XML/bestanden/3_34_afgeleid_van_product.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblio xmlns="http://www.vdab.be/XML" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.vdab.be/XML 3_33_afgeleid_van_product.xsd">
	<boek id="405">
		<titel>Database Programming with C#</titel>
		<schrijver>Thomsen</schrijver>
		<uitgever>Apress</uitgever>
		<isbn_nr>1590590104</isbn_nr>
	</boek>
	<cd id="300">
		<titel>De vier seizoenen</titel>
		<uitvoerder>Filharmonisch orkest van de VRT</uitvoerder>
		<tekstschrijver></tekstschrijver>
		<componist>Vivaldi</componist>
	</cd>
</biblio>
