=== switch87/VDAB/XML/bestanden/3_4_met_attributen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT stamboom (persoon+)>
<!ELEMENT persoon (voornaam, familienaam)>
<!ATTLIST persoon 
	nr ID #REQUIRED 
	geslacht (Man|Vrouw) #REQUIRED 
	vader IDREF #IMPLIED  
	kinderen IDREFS #IMPLIED
	email CDATA #FIXED "info@kiekeboe.be">
<!ELEMENT voornaam (#PCDATA)> 
<!ELEMENT familienaam (#PCDATA)>

=== switch87/VDAB/XML/bestanden/3_5_met_attributen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stamboom SYSTEM "3_4_met_attributen.dtd">
<stamboom>
	<persoon nr="k1" geslacht="Man" kinderen="k2 k3" email="info@kiekeboe.be">
		<voornaam>Marcel</voornaam>
		<familienaam>Kiekeboe</familienaam>
	</persoon>
	<persoon nr="k2" geslacht="Vrouw" vader="k1" email="info@kiekeboe.be">
		<voornaam>Fanny</voornaam>
		<familienaam>Kiekeboe</familienaam>
	</persoon>
	<persoon nr="k3" geslacht="Man" vader="k1" email="info@kiekeboe.be">
		<voornaam>Konstantinopel</voornaam>
		<familienaam>Kiekeboe</familienaam>
	</persoon>
</stamboom>
